### PR TITLE
Fix linkedIn new profile html

### PR DESCRIPTION
**Pull request by lcalvy**
Hello, 

No way to have test running but tested locally with my real linkedin profile

### CODE REVIEW

**Comment by nilsonivano** [comment]
Hey @lcalvy thanks for the fix!

**Comment by nandunbandara** [comment]
Hi @leonardiwagner is this not released yet? I think the latest version out there is still 1.0.21 if I'm right.

**Comment by asafm** [comment]
No release?

**Comment by ghost** [comment]
Would be great to have this repo updated to include fix @leonardiwagner :)

A thousand thank you's @lcalvy

**Comment by ss-zheng** [comment]
Still no fix?

**Pull request merged**
